In [1]:
#Import Library
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier, IsolationForest
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import joblib
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("final_global_economy_data.csv")

df.head()

,Year,Country,Core_CPI,Inflation,Exports,Foreign_Reserves,GDP,Imports,Industrial_Production,Exchange_Rate,...,GDP_Growth,Export_Growth,Import_Growth,Stock_Growth,Exchange_Rate_Change,Inflation_Lag,GDP_Growth_Lag,Unemployment_Lag,GDP_Growth_Rolling_3Y,Inflation_Rolling_3Y
0,1999,Advanced Economies,101.8832,1.737984,5409369.0,0.290025,35985399.0,6105051.0,8.500000e+12,7.546392,...,3.343484,5.203289,7.892143,0.0,0.0,1.909170,2.565513,6.683189,1.969666,1.920070
1,2000,Advanced Economies,101.8832,2.701247,6064090.0,0.280050,37467104.0,6773346.0,8.920000e+12,7.546392,...,4.117517,12.103463,10.946592,0.0,0.0,1.737984,3.343484,6.379832,3.342172,2.116134
2,2001,Advanced Economies,101.8832,2.665014,6062661.0,0.301574,38025964.0,6772880.0,8.730000e+12,7.546392,...,1.491602,-0.023565,-0.006880,0.0,0.0,2.701247,4.117517,5.945781,2.984201,2.368082
3,2002,Advanced Economies,101.8832,2.068841,6353687.0,0.338647,38590851.0,7152648.0,8.750000e+12,7.546392,...,1.485530,4.800301,5.607186,0.0,0.0,2.665014,1.491602,6.083438,2.364883,2.478367
4,2003,Advanced Economies,101.8832,2.054477,6639058.0,0.356308,39328920.0,7449024.0,8.890000e+12,7.546392,...,1.912549,4.491424,4.143584,0.0,0.0,2.068841,1.485530,6.633609,1.629894,2.262777

In [3]:
df.shape

(2053, 28)

In [ ]:
df.info()

In [5]:
df.describe()

,Year,Core_CPI,Inflation,Exports,Foreign_Reserves,GDP,Imports,Industrial_Production,Exchange_Rate,Retail_Sales,...,GDP_Growth,Export_Growth,Import_Growth,Stock_Growth,Exchange_Rate_Change,Inflation_Lag,GDP_Growth_Lag,Unemployment_Lag,GDP_Growth_Rolling_3Y,Inflation_Rolling_3Y
count,2053.000000,2053.000000,2053.000000,2.053000e+03,2053.000000,2.053000e+03,2.053000e+03,2.053000e+03,2053.000000,2053.000000,...,2053.000000,2053.000000,2053.000000,2053.000000,2053.000000,2053.000000,2053.000000,2053.000000,2053.000000,2053.000000
mean,2012.624939,115.329478,3.808007,8.527909e+05,0.567425,3.986202e+06,9.084736e+05,1.049168e+12,583.525672,94.522453,...,2.757601,2.546920,3.703719,6.814501,1.701536,3.829499,2.816054,7.988974,2.778383,3.828885
std,8.011420,77.002136,0.895389,2.224216e+06,0.497692,1.174918e+07,2.467012e+06,2.953401e+12,2748.048206,31.110478,...,4.098857,8.253718,26.414829,24.797844,10.962148,0.928003,4.122243,5.435050,2.768916,0.815048
min,1999.000000,48.579160,0.086131,5.688951e+01,0.005582,7.001027e+03,1.993515e+03,1.470000e+09,0.071688,12.411410,...,-21.253414,-40.088986,-84.345500,-86.186180,-28.146297,0.086131,-21.253414,0.650833,-7.965550,0.295112
25%,2006.000000,99.127020,3.753451,1.691524e+05,0.165201,1.344797e+05,1.156298e+05,3.360000e+10,2.442666,91.926930,...,0.763007,0.000000,0.000000,-4.619707,-3.304069,3.753451,0.998207,4.850000,1.181790,3.753451
50%,2013.000000,101.883200,3.753451,2.432245e+05,0.432026,3.686502e+05,2.201580e+05,9.760000e+10,7.546392,91.926930,...,2.663303,0.000000,0.000000,0.000000,0.000000,3.753451,2.758754,6.891667,2.523270,3.753451
75%,2020.000000,111.030500,3.753451,4.061691e+05,0.800466,1.555093e+06,4.115222e+05,3.770000e+11,43.920970,93.742350,...,4.692889,4.356053,5.442178,17.522756,4.338788,3.753451,4.716849,8.700000,4.121147,3.753451
max,2026.000000,1606.210000,14.581400,1.755161e+07,2.805320,9.326367e+07,2.333341e+07,2.340000e+13,26211.300000,367.451100,...,105.487934,166.037364,944.376427,407.677115,186.625885,14.581400,105.487934,37.249970,37.735958,14.594587

In [ ]:
missing = df.isnull().sum().sort_values(ascending=False)
missing

In [7]:
df = df.sort_values(["Country", "Year"]).reset_index(drop=True)
df.head()

,Year,Country,Core_CPI,Inflation,Exports,Foreign_Reserves,GDP,Imports,Industrial_Production,Exchange_Rate,...,GDP_Growth,Export_Growth,Import_Growth,Stock_Growth,Exchange_Rate_Change,Inflation_Lag,GDP_Growth_Lag,Unemployment_Lag,GDP_Growth_Rolling_3Y,Inflation_Rolling_3Y
0,1999,Advanced Economies,101.8832,1.737984,5409369.0,0.290025,35985399.0,6105051.0,8.500000e+12,7.546392,...,3.343484,5.203289,7.892143,0.0,0.0,1.909170,2.565513,6.683189,1.969666,1.920070
1,2000,Advanced Economies,101.8832,2.701247,6064090.0,0.280050,37467104.0,6773346.0,8.920000e+12,7.546392,...,4.117517,12.103463,10.946592,0.0,0.0,1.737984,3.343484,6.379832,3.342172,2.116134
2,2001,Advanced Economies,101.8832,2.665014,6062661.0,0.301574,38025964.0,6772880.0,8.730000e+12,7.546392,...,1.491602,-0.023565,-0.006880,0.0,0.0,2.701247,4.117517,5.945781,2.984201,2.368082
3,2002,Advanced Economies,101.8832,2.068841,6353687.0,0.338647,38590851.0,7152648.0,8.750000e+12,7.546392,...,1.485530,4.800301,5.607186,0.0,0.0,2.665014,1.491602,6.083438,2.364883,2.478367
4,2003,Advanced Economies,101.8832,2.054477,6639058.0,0.356308,39328920.0,7449024.0,8.890000e+12,7.546392,...,1.912549,4.491424,4.143584,0.0,0.0,2.068841,1.485530,6.633609,1.629894,2.262777

# Page 1 - Global Overview

In [9]:
#KPI Cards data
latest_year = df["Year"].max()
latest_data = df[df["Year"] == latest_year]

global_kpi= {
    "Latest Year": latest_year,
    "Average GDP": latest_data["GDP"].mean(),
    "Average Inflation": latest_data["Inflation"].mean(),
    "Average Unemployment": latest_data["Unemployment"].mean(),
    "Average GDP Growth": latest_data["GDP_Growth"].mean()
}

global_kpi

{'Latest Year': np.int64(2026),
 'Average GDP': np.float64(5394021.742567568),
 'Average Inflation': np.float64(3.5041841216216207),
 'Average Unemployment': np.float64(6.291477337837838),
 'Average GDP Growth': np.float64(0.0)}

In [ ]:
# Global GDP Trend

global_gdp = df.groupby("Year")["GDP"].mean().reset_index()

fig=px.line(
    global_gdp,
    x="Year",
    y="GDP",
    title="Average Global GDP Trend"
)

fig.show()

In [ ]:
#Unemployment Trend
global_unemployment = df.groupby("Year")["Unemployment"].mean().reset_index()

fig=px.line(
    global_unemployment,
    x="Year",
    y="Unemployment",
    title="Average Global Unemployment Trend"
)

fig.show()

# Page 2 - Country Comparison

In [ ]:
#Select Countries
selected_countries= ["United States", "China", "Germany", "India", "Brazil"]
comparison_df=df[df["Country"].isin(selected_countries)]
comparison_df.head()

In [ ]:
#Compare GDP by Country
fig= px.line(
    comparison_df,
    x="Year",
    y="GDP",
    color="Country",
    title="GDP Comparison by Country"
)

fig.show()

In [ ]:
#Compare Inflation by Country
fig= px.line(
    comparison_df,
    x="Year",
    y="Inflation",
    color="Country",
    title="Inflation Comparison by Country"
)

fig.show()

In [ ]:
#Country Ranking by GDP
gdp_ranking = latest_data[["Country", "GDP"]].sort_values(by="GDP", ascending=False)
gdp_ranking.head(10)

In [17]:
#Economic Score
score_df = latest_data.copy()

score_features = [
    "GDP_Growth",
    "Inflation",
    "Unemployment",
    "Trade_Balance",
    "Total_Reserves",
    "Stock_Growth"
]

score_df = score_df.dropna(subset=score_features)

score_df["GDP_Growth_Score"] = score_df["GDP_Growth"].rank(pct=True)
score_df["Inflation_Score"] = 1 - score_df["Inflation"].rank(pct=True)
score_df["Unemployment_Score"] = 1 - score_df["Unemployment"].rank(pct=True)
score_df["Trade_Score"] = score_df["Trade_Balance"].rank(pct=True)
score_df["Reserve_Score"] = score_df["Total_Reserves"].rank(pct=True)
score_df["Stock_Score"] = score_df["Stock_Growth"].rank(pct=True)

score_df["Economic_Health_Score"] = (
    score_df["GDP_Growth_Score"] * 0.25 +
    score_df["Inflation_Score"] * 0.20 +
    score_df["Unemployment_Score"] * 0.20 +
    score_df["Trade_Score"] * 0.15 +
    score_df["Reserve_Score"] * 0.10 +
    score_df["Stock_Score"] * 0.10
) * 100

score_ranking = score_df[["Country", "Economic_Health_Score"]].sort_values(
    "Economic_Health_Score", ascending=False
)

score_ranking.head(10)

                             Country  Economic_Health_Score
470         EMDE East Asia & Pacific              72.533784
1111                     Korea, Rep.              68.682432
1027                           Japan              67.804054
1608                       Singapore              67.331081
1275                          Mexico              66.858108
1580              Russian Federation              66.452703
1829                   Taiwan, China              66.385135
526   EMDE Latin America & Caribbean              64.155405
1414                          Norway              60.844595
804            High Income Countries              60.777027

# Page 3- Trade Analysis

In [ ]:
# Export Trend
export_trend=df.groupby("Year")["Exports"].mean().reset_index()

fig=px.line(
    export_trend,
    x="Year",
    y="Exports",
    title="Average Global Export Trend"
)

fig.show()

In [ ]:
# Import Trend
import_trend= df.groupby("Year")["Imports"].mean().reset_index()

fig = px.line(
    import_trend,
    X="Year",
    y="Imports",
    title="Average Global Import Trend"
)

fig.show()

In [ ]:
#Trade Balance
trade_balance_trend= df.groupby("Year")["Trade_Balance"].mean().reset_index()

fig=px.line(
    trade_balance_trend,
    X="Year",
    y="Trade_Balance",
    title= " Average Global Trade Balance"
)

fig.show()

In [ ]:
# Top Trade Surplus Countries
top_surplus = latest_data["Country", "Trade_Balance"].sort_values(
    "Trade_Balance", ascending=False
)

top_surplus.head(10)

In [ ]:
#Top Trade Deficit Countries
top_deficit = latest_date["Country","Trade_Balance"].sort_values(
    "Trade_Balance", ascending=True
)

top_deficit.head(10)

# Page 4 - Stock Market Trend

In [ ]:
# Reserves Trend
reserve_trend = df.groupby("Year")["Total_Reserves"].mean().reset_index()

fig = px.line(
    reserve_trend,
    x="Year",
    y="Total_Reserves",
    title="Average Global Total Reserves"
)

fig.show()

In [ ]:
#Stock Market Trend
stock_trend = df.groupby("Year")["Stock_Market"].mean().reset_index()

fig = px.line(
    stock_trend,
    x="Year",
    y="Stock_Market",
    title="Average Global Stock Market Trend"
)

fig.show()

In [ ]:
#Exchange Rate Trend
exchange_trend = df.groupby("Year")["Exchange_Rate"].mean().reset_index()

fig = px.line(
    exchange_trend,
    x="Year",
    y="Exchange_Rate",
    title="Average Global Exchange Rate Trend"
)

fig.show()

# Page 5 - AI Prediction

In [18]:
inflation_features = [
    "GDP",
    "GDP_Growth",
    "Unemployment",
    "Trade_Balance",
    "Exchange_Rate",
    "Stock_Growth",
    "Inflation_Lag",
    "GDP_Growth_Lag",
    "Unemployment_Lag"
]

target = "Inflation"

ml_df = df.dropna(subset=inflation_features + [target])

X = ml_df[inflation_features]
y = ml_df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [19]:
# Train Inflation Model
inflation_model = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    max_depth=10
)

inflation_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, n_estimators=300, random_state=42)

In [21]:
#Evaluate Inflation Model
y_pred = inflation_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 0.14408937031735822
RMSE: 0.586610483319271
R2 Score: 0.4852328264132597

In [22]:
#Feature Importance
importance_df = pd.DataFrame({
    "Feature": inflation_features,
    "Importance": inflation_model.feature_importances_
}).sort_values("Importance", ascending=False)

importance_df

            Feature  Importance
6     Inflation_Lag    0.583568
7    GDP_Growth_Lag    0.128063
0               GDP    0.077932
8  Unemployment_Lag    0.059915
1        GDP_Growth    0.054445
3     Trade_Balance    0.048608
2      Unemployment    0.041027
5      Stock_Growth    0.006299
4     Exchange_Rate    0.000143

In [23]:
importance_df = pd.DataFrame({
    "Feature": inflation_features,
    "Importance": inflation_model.feature_importances_
}).sort_values("Importance", ascending=False)

importance_df

            Feature  Importance
6     Inflation_Lag    0.583568
7    GDP_Growth_Lag    0.128063
0               GDP    0.077932
8  Unemployment_Lag    0.059915
1        GDP_Growth    0.054445
3     Trade_Balance    0.048608
2      Unemployment    0.041027
5      Stock_Growth    0.006299
4     Exchange_Rate    0.000143

In [24]:
# Recession Probability
df["Recession"] = np.where(
    (df["GDP_Growth"] < 0) | 
    ((df["GDP_Growth"] < 1) & (df["Unemployment"] > df["Unemployment"].median())),
    1,
    0
)

df[["Country", "Year", "GDP_Growth", "Unemployment", "Recession"]].head()

              Country  Year  GDP_Growth  Unemployment  Recession
0  Advanced Economies  1999    3.343484      6.379832          0
1  Advanced Economies  2000    4.117517      5.945781          0
2  Advanced Economies  2001    1.491602      6.083438          0
3  Advanced Economies  2002    1.485530      6.633609          0
4  Advanced Economies  2003    1.912549      6.816206          0

In [25]:
#Train Recession Model
df["Recession"] = np.where(
    (df["GDP_Growth"] < 0) | 
    ((df["GDP_Growth"] < 1) & (df["Unemployment"] > df["Unemployment"].median())),
    1,
    0
)

df[["Country", "Year", "GDP_Growth", "Unemployment", "Recession"]].head()

              Country  Year  GDP_Growth  Unemployment  Recession
0  Advanced Economies  1999    3.343484      6.379832          0
1  Advanced Economies  2000    4.117517      5.945781          0
2  Advanced Economies  2001    1.491602      6.083438          0
3  Advanced Economies  2002    1.485530      6.633609          0
4  Advanced Economies  2003    1.912549      6.816206          0

In [28]:
#Train Recession Model
recession_feature=[
    "Inflation",
    "GDP_Growth",
    "Unemployment",
    "Trade_Balance",
    "Exchange_Rate",
    "Stock_Growth",
    "Inflation_Lag",
    "GDP_Growth_Lag",
    "Unemployment_Lag",
    "GDP_Growth_Rolling_3Y",
    "Inflation_Rolling_3Y",
]

rec_df =df.dropna(subset=recession_feature + ["Recession"])

X=rec_df[recession_feature]
y=rec_df["Recession"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42, stratify=y)

recession_model=RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    max_depth = 8,
    class_weight= "balanced"
)

recession_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=8, n_estimators=300,
                       random_state=42)

In [29]:
# Evaluate Recession Model
y_pred = recession_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       341
           1       1.00      1.00      1.00        70

    accuracy                           1.00       411
   macro avg       1.00      1.00      1.00       411
weighted avg       1.00      1.00      1.00       411

In [31]:
#Recession Probability
rec_df["Recession_Probability"] = recession_model.predict_proba(
    rec_df[recession_feature]
)[:, 1]

rec_df[["Country", "Year", "Recession_Probability"]].head()

              Country  Year  Recession_Probability
0  Advanced Economies  1999               0.000360
1  Advanced Economies  2000               0.000639
2  Advanced Economies  2001               0.000639
3  Advanced Economies  2002               0.000854
4  Advanced Economies  2003               0.016217

In [32]:
#Forecast Next 3 Years
def forecast_next_3_years(country_name, target_col):
    country_df = df[df["Country"] == country_name].sort_values("Year")
    
    country_df = country_df.dropna(subset=[target_col])
    
    last_year = country_df["Year"].max()
    last_values = country_df[target_col].tail(3).values
    
    avg_growth = country_df[target_col].pct_change().replace([np.inf, -np.inf], np.nan).dropna().tail(5).mean()
    
    forecasts = []
    current_value = country_df[target_col].iloc[-1]
    
    for i in range(1, 4):
        next_year = last_year + i
        next_value = current_value * (1 + avg_growth)
        
        forecasts.append({
            "Country": country_name,
            "Year": next_year,
            "Forecast_Target": target_col,
            "Forecast_Value": next_value
        })
        
        current_value = next_value
    
    return pd.DataFrame(forecasts)

In [33]:
# Forecast Example
forecast_gdp = forecast_next_3_years("Indonesia", "GDP")
forecast_inflation = forecast_next_3_years("Indonesia", "Inflation")

forecast_result = pd.concat([forecast_gdp, forecast_inflation])

forecast_result

     Country  Year Forecast_Target  Forecast_Value
0  Indonesia  2027             GDP    1.490152e+06
1  Indonesia  2028             GDP    1.551186e+06
2  Indonesia  2029             GDP    1.614719e+06
0  Indonesia  2027       Inflation    3.753451e+00
1  Indonesia  2028       Inflation    3.753451e+00
2  Indonesia  2029       Inflation    3.753451e+00

# Page 6 - Global Risk Intelligence

In [ ]:
#Risk Score
risk_df = latest_data.copy()

risk_features = [
    "Inflation",
    "Unemployment",
    "Exchange_Rate_Change",
    "Stock_Growth",
    "GDP_Growth",
    "Trade_Balance"
]

risk_df = risk_df.dropna(subset=risk_features)

risk_df["Inflation_Risk"] = risk_df["Inflation"].rank(pct=True)
risk_df["Unemployment_Risk"] = risk_df["Unemployment"].rank(pct=True)
risk_df["Exchange_Risk"] = risk_df["Exchange_Rate_Change"].abs().rank(pct=True)
risk_df["Stock_Risk"] = 1 - risk_df["Stock_Growth"].rank(pct=True)
risk_df["GDP_Risk"] = 1 - risk_df["GDP_Growth"].rank(pct=True)
risk_df["Trade_Risk"] = 1 - risk_df["Trade_Balance"].rank(pct=True)

risk_df["Global_Risk_Score"] = (
    risk_df["Inflation_Risk"] * 0.20 +
    risk_df["Unemployment_Risk"] * 0.20 +
    risk_df["Exchange_Risk"] * 0.15 +
    risk_df["Stock_Risk"] * 0.15 +
    risk_df["GDP_Risk"] * 0.20 +
    risk_df["Trade_Risk"] * 0.10
) * 100

risk_df["Risk_Level"] = pd.cut(
    risk_df["Global_Risk_Score"],
    bins=[0, 40, 70, 100],
    labels=["Low Risk", "Medium Risk", "High Risk"]
)

risk_df[["Country", "Global_Risk_Score", "Risk_Level"]].sort_values(
    "Global_Risk_Score", ascending=False
).head(10)

                     Country  Global_Risk_Score   Risk_Level
1912                  Turkey          70.675676    High Risk
332                 Colombia          70.337838    High Risk
1774                  Sweden          67.770270  Medium Risk
1386         North Macedonia          64.391892  Medium Risk
1691            South Africa          64.189189  Medium Risk
165   Bosnia and Herzegovina          63.750000  Medium Risk
1220                Malaysia          63.716216  Medium Risk
665                  Estonia          62.635135  Medium Risk
721                   France          60.472973  Medium Risk
1719                   Spain          59.797297  Medium Risk

In [42]:
#Anomaly Detection
anomaly_features = [
    "GDP_Growth",
    "Inflation",
    "Unemployment",
    "Exchange_Rate_Change",
    "Trade_Balance",
    "Stock_Growth"
]

anomaly_df = df.dropna(subset=anomaly_features).copy()
iso_model= IsolationForest(
    contamination=0.08,
    random_state=42
)

anomaly_df["Anomaly"] = iso_model.fit_predict(anomaly_df[anomaly_features])
anomaly_df["Anomaly_Label"] = anomaly_df["Anomaly"].map({
    1:"Normal",
    -1: "Anomaly"
})

anomaly_df[["Country","Year","Anomaly_Label"]].head()

              Country  Year Anomaly_Label
0  Advanced Economies  1999        Normal
1  Advanced Economies  2000        Normal
2  Advanced Economies  2001        Normal
3  Advanced Economies  2002        Normal
4  Advanced Economies  2003        Normal

In [43]:
# Crisis Alerts
alert_df = risk_df.copy()

alert_df["Crisis_Alert"] = np.where(
    alert_df["Global_Risk_Score"] >= 70,
    "High Alert",
    np.where(
        alert_df["Global_Risk_Score"] >= 40,
        "Watchlist",
        "Stable"
    )
)

alert_df[["Country", "Global_Risk_Score", "Risk_Level", "Crisis_Alert"]].sort_values(
    "Global_Risk_Score", ascending=False
).head(15)

                     Country  Global_Risk_Score   Risk_Level Crisis_Alert
1912                  Turkey          70.675676    High Risk   High Alert
332                 Colombia          70.337838    High Risk   High Alert
1774                  Sweden          67.770270  Medium Risk    Watchlist
1386         North Macedonia          64.391892  Medium Risk    Watchlist
1691            South Africa          64.189189  Medium Risk    Watchlist
165   Bosnia and Herzegovina          63.750000  Medium Risk    Watchlist
1220                Malaysia          63.716216  Medium Risk    Watchlist
665                  Estonia          62.635135  Medium Risk    Watchlist
721                   France          60.472973  Medium Risk    Watchlist
1719                   Spain          59.797297  Medium Risk    Watchlist
1470             Philippines          59.324324  Medium Risk    Watchlist
277                    Chile          58.986486  Medium Risk    Watchlist
1138                  Latvia          58.040541  Medium Risk    Watchlist
693                  Finland          57.972973  Medium Risk    Watchlist
55                 Australia          57.702703  Medium Risk    Watchlist

# Page 7 - Country Clustering

In [37]:
# Prepare Clustering Data
cluster_features = [
    "GDP",
    "GDP_Growth",
    "Inflation",
    "Unemployment",
    "Trade_Balance",
    "Total_Reserves",
    "Stock_Growth"
]

cluster_df = latest_data.dropna(subset=cluster_features).copy()

X_cluster = cluster_df[cluster_features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_cluster)

In [38]:
#Kmeans Clustering
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)

cluster_df["Cluster"] = kmeans.fit_predict(X_scaled)

cluster_df[["Country", "Cluster"]].head()

                Country  Cluster
27   Advanced Economies        1
55            Australia        2
83              Austria        0
110             Belarus        2
138             Belgium        2

In [39]:
#PCA Visualization
pca = PCA(n_components=2)

pca_result = pca.fit_transform(X_scaled)

cluster_df["PCA1"] = pca_result[:, 0]
cluster_df["PCA2"] = pca_result[:, 1]

fig = px.scatter(
    cluster_df,
    x="PCA1",
    y="PCA2",
    color="Cluster",
    hover_name="Country",
    title="Country Economic Segmentation using PCA"
)

fig.show()

In [40]:
#Cluster Profile
cluster_profile = cluster_df.groupby("Cluster")[cluster_features].mean()

cluster_profile

,GDP,GDP_Growth,Inflation,Unemployment,Trade_Balance,Total_Reserves,Stock_Growth
Cluster,,,,,,,
0,8.128885e+05,0.0,3.753451,5.738420,2.544538e+04,1.646222e+05,31.854607
1,5.595838e+07,0.0,1.785264,5.536070,-2.537681e+06,9.075867e+06,2.138776
2,2.426583e+06,0.0,3.579465,5.448831,-3.000159e+05,3.997030e+05,7.901988
3,9.840609e+05,0.0,2.843768,32.354390,3.371100e+03,1.215659e+05,15.808824

# Save Outputs for Streamlit

In [45]:
# Save Models
joblib.dump(inflation_model, "inflation_model.pkl")
joblib.dump(recession_model, "recession_model.pkl")
joblib.dump(iso_model, "anomaly_model.pkl")
joblib.dump(kmeans, "kmeans_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(pca, "pca_model.pkl")

['pca_model.pkl']

In [46]:
#Save Processed Data
df.to_csv("processed_global_economy_data.csv", index=False)
risk_df.to_csv("risk_score_data.csv", index=False)
score_df.to_csv("economic_score_data.csv", index=False)
cluster_df.to_csv("country_cluster_data.csv", index=False)
anomaly_df.to_csv("anomaly_detection_data.csv", index=False)
rec_df.to_csv("recession_probability_data.csv", index=False)

In [47]:
# Final Check
print("Notebook completed successfully.")
print("Files saved for Streamlit dashboard:")
print("- processed_global_econ omy_data.csv")
print("- risk_score_data.csv")
print("- economic_score_data.csv")
print("- country_cluster_data.csv")
print("- anomaly_detection_data.csv")
print("- recession_probability_data.csv")
print("- inflation_model.pkl")
print("- recession_model.pkl")
print("- anomaly_model.pkl")
print("- kmeans_model.pkl")
print("- scaler.pkl")
print("- pca_model.pkl")

Notebook completed successfully.
Files saved for Streamlit dashboard:
- processed_global_econ omy_data.csv
- risk_score_data.csv
- economic_score_data.csv
- country_cluster_data.csv
- anomaly_detection_data.csv
- recession_probability_data.csv
- inflation_model.pkl
- recession_model.pkl
- anomaly_model.pkl
- kmeans_model.pkl
- scaler.pkl
- pca_model.pkl